# Generated by Django 5.2.17 on 2026-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-id'], 'verbose_name': 'conversation'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New chat', max_length=100),
        ),
    ]
