# Generated by Django 5.2.17 on 2026-09-18 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_conversation_options_alter_conversation_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('stage', models.CharField(default='Waiting for the GPU', max_length=200)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_edit_results', to='portal.document')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_edits', to='portal.document')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('owner',), name='one_active_image_edit_per_user')],
            },
        ),
    ]
