# Generated by Django 5.2.17 on 2026-09-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model_id',
            field=models.CharField(default='Qwen3.8-27B-Uncensored', max_length=100),
        ),
    ]
