# Generated by Django 5.2.17 on 2026-09-20 02:59

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_conversation_model_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='fl2va', max_length=16)),
                ('prompt', models.TextField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('stage', models.CharField(default='Waiting for the GPU', max_length=200)),
                ('video', models.FileField(blank=True, upload_to=portal.models.upload_path)),
                ('audio', models.FileField(blank=True, upload_to=portal.models.upload_path)),
                ('size', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.document')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('owner',), name='one_active_video_per_user')],
            },
        ),
    ]
