# Generated by Django 5.2.17 on 2026-09-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_videojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='completed_segments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videojob',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='videojob',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
    ]
