# Generated by Django 5.2.17 on 2026-09-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_videojob_completed_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=16),
        ),
    ]
