# Generated by Django 5.2.17 on 2026-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_videojob_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='segment_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='videojob',
            name='timed_segments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
