# Generated by Django 5.2.17 on 2026-09-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_videojob_segment_seconds_videojob_timed_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='resolution',
            field=models.CharField(default='288p', max_length=8),
        ),
    ]
