# Generated by Django 5.2.17 on 2026-09-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_videojob_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
