# Generated by Django 5.2.17 on 2026-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_videojob_delete_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
