# Generated by Django 5.2.17 on 2026-09-20 20:45

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_videojob_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpscaleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveIntegerField(default=1080)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('stage', models.CharField(default='Waiting for the GPU', max_length=200)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, upload_to=portal.models.upload_path)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upscales', to='portal.videojob')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('owner',), name='one_active_upscale_per_user')],
            },
        ),
    ]
