# Generated by Django 5.2.17 on 2026-09-20 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_videoupscalejob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videojob',
            name='one_active_video_per_user',
        ),
        migrations.AddConstraint(
            model_name='videojob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('owner',), name='one_running_video_per_user'),
        ),
    ]
