# Generated by Django 5.2.17 on 2026-09-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_videojob_one_active_video_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='continuation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuations', to='portal.videojob'),
        ),
        migrations.AddField(
            model_name='videojob',
            name='prefix_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
