# Generated by Django 5.2.17 on 2026-09-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_videojob_continuation_of_videojob_prefix_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('format', models.CharField(default='square', max_length=16)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('stage', models.CharField(default='Waiting for the GPU', max_length=200)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_results', to='portal.document')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_sources', to='portal.document')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
