# Generated by Django 5.2.17 on 2026-09-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_photojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupscalejob',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
