# Generated by Django 5.2.17 on 2026-09-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_videoupscalejob_delete_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='model',
            field=models.CharField(default='qwen21', max_length=32),
        ),
    ]
