# Generated by Django 5.2.17 on 2026-09-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_photojob_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
