# Generated by Django 5.2.17 on 2026-09-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_photojob_delete_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='negative_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
