# Generated by Django 5.2.17 on 2026-09-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_photojob_negative_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_references', to='portal.document')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='portal.photojob')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('job', 'document'), name='photo_unique_reference'), models.UniqueConstraint(fields=('job', 'position'), name='photo_reference_position')],
            },
        ),
    ]
