# Generated by Django 5.2.17 on 2026-09-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_photoreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='seed',
            field=models.PositiveIntegerField(default=42),
        ),
    ]
